env:
  global:
   - secure: "VrgSZAgTRTdH1rq0OHXHtArOA5SyLsJX9YA9O5c+PSXI/drMjc3pGsTIK3NA7xcyGaEIT+DjzV36yxvAz/3uurYkFtiz/sl1suziy6nSNBqvQSE01lBU9GnqHpkPg6/alnijG0Bf3KvXTdw5MmRaK+f9corNJAa+s1sP0rP7WMQ="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language: cpp
branches:
  only:
  - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: hypro
    - DOXYFILE: $TRAVIS_BUILD_DIR/build/doc/Doxygen
    - GH_REPO_REF: github.com/hypro/hypro.git

notifications:
  email:
    recipients:
      - stefan.schupp@cs.rwth-aachen.de
  slack:
    rooms:
      - hypro:v2n2cgATRJJYPctLTL1MSfOn#github

sudo: required

cache:
  apt: true
  directories:
    - $HOME/usr/
    - $HOME/.sonar/cache
    - build/resources

addons:
  apt:
    sources: &sources_base
      - boost-latest
      - ubuntu-toolchain-r-test
    packages: &packages_base
      - libboost1.55-all-dev
      - libeigen3-dev
      - libgmp-dev
      - libgtest-dev
      - uuid-dev
      - openjdk-9-jre
      - g++-6

matrix:
  include:
    #- os: linux
    #  compiler: gcc
    #  env: COMPILER=g++-4.9
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-5, doxygen]
      env: COMPILER=g++-5 FLAGS=-DCREATE_DOC=ON
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: [*sources_base]
          packages: [*packages_base, g++-6, lcov]
      env: COMPILER=g++-6 FLAGS=-DHYPRO_COVERAGE=ON
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        sonarcloud:
          organization: "hypro-github"
          token:
            secure: ${SONAR_TOKEN}
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.6]
          packages: [*packages_base, clang-3.6, lcov]
      env: COMPILER=clang++-3.6 TASK=sonarcloud
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.7]
          packages: [*packages_base, clang-3.7]
      env: COMPILER=clang++-3.7
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: [*sources_base, llvm-toolchain-precise-3.8]
          packages: [*packages_base, clang-3.8]
      env: COMPILER=clang++-3.8
    #- os: osx
    #  osx_image: xcode6.4
    #  compiler: clang
    #  env: COMPILER=clang++
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang++
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: COMPILER=clang++

before_install:
  - cd .travis/ && source setupTravis.sh && cd ../
  - sudo motion update || echo 'up to date'

install:
  - git clone https://github.com/smtrat/carl.git && cd carl && mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release .. && make resources && make lib_carl VERBOSE=1

script:
  - cd ${TRAVIS_BUILD_DIR}
  - .travis/build.sh
  #- mkdir build && cd build && cmake $FLAGS -DCMAKE_CXX_COMPILER=$COMPILER .. && make resources && make VERBOSE=1
  #- cat /home/travis/build/hypro/hypro/src/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-out.log
  #- cat /home/travis/build/hypro/hypro/src/resources/antlr_build/src/antlr4cpp-stamp/antlr4cpp-build-err.log
  #- make test

# Generate and deploy documentation
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x .travis/buildDoc.sh
  - ./.travis/buildDoc.sh
  # coveralls
  - chmod +x processCoverage.sh
  - ./processCoverage.sh
